### ISSUE TITLE
shows `error while loading shared libraries: libRDKitDataStructs.so.1: cannot open shared object file: No such file or directory error: test failed, to rerun pass '--test test_descriptors'`

### ISSUE THREAD

**Issue by goldwind-ting** [rdkit-rs/rdkit#1]
rust:
rustc 1.61.0
rdkit:
rdkit-2022.03.1

**Comment by xrl** [comment]
Interesting, I would have thought that library is on all recent installs. Can you give a listing of all your `*.so` files.

**Comment by goldwind-ting** [comment]
I have resolved the issue, I used ubuntu, the library `rdkit` is installed in `/usr/local`, but the `library_root` in the `build.rs`(in lib rdkit_sys) is `/usr`.
So could you change the `library_root` to `/usr/local` for linux in the library `rdkit_sys`?

**Comment by pstjohn** [comment]
I also encountered this issue when using `dynamic-linking-from-conda` under WSL2. Setting 
```export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH```
let rust find the rdkit libraries at runtime.

**Comment by xrl** [comment]
There's been a regression in conda support in CI so it's not a big surprise to me that it stopped working. For whatever reason the conda registry doesn't trust our CI and we can no longer pull down prebuilt rdkit.

This coincides with a bit of refactoring on the flakey build.rs that makes rdkit-sys tick. I would be happy to accept PRs that fix CI -- we don't use conda but maybe we should.
